### ISSUE TITLE
Citycom: Neocronicle/StockX

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#402] opened 2020-11-02 07:43 UTC
The categories Neocronicle and StockX in the Citycom are useless why dont remove it ?

Neocronicle:
![shot0000](https://user-images.githubusercontent.com/32795552/97842123-673ce800-1ce7-11eb-8090-c25fe5e2fd2d.png)
StockX:
![shot0001](https://user-images.githubusercontent.com/32795552/97842139-6c9a3280-1ce7-11eb-9187-a46d523bd91c.png)

**Comment by NCC-Lykos** [comment] 2021-11-02 14:49
They are placeholders for now. We have plans to do something with those areas, it will just take time.

Closing as not a bug.

**Closed as completed by NCC-Lykos** 2021-11-02 14:49 UTC
