### ISSUE TITLE
Low FPS in wasteland zones

### ISSUE THREAD

**Issue by NCC-Vali** [NCC-Lykos/neocron-classic#219] opened 2018-03-07 04:56 UTC
Currently getting 20-35 FPS in wasteland zones. This has happened sometime in the past 6 months, as before then I had no issues.

Tried reinstalling drivers, etc, with no effect. An old (~6 months ago), unpatched dev client I have runs fine.

i7 3770K
16gb DDR3
GTX 1070 FE
Win10x64

**Comment by NCC-Lykos** [comment] 2018-03-12 17:00
Shoulda bought that 1080 Ti homie.

**Comment by M-ace** [comment] 2018-03-12 18:31
try going into nvidia settings and changing a few things from application controlled to nvidia controlled.  that helped me a ton with fps

**Comment by NCC-Lykos** [comment] 2018-07-06 17:01
Any update on this? Maybe a list of wasteland zones that this occurs in? I'll be closing this as unable to reproduce if nothing new.

**Comment by NCC-Therenall** [comment] 2018-07-08 05:49
I'm going to close this, so far I haven't found anyone who can reproduce the issue. If it is something we can find I'll be happy to re-open it.

**Closed as completed by NCC-Therenall** 2018-07-08 05:49 UTC
Labels: Source Dev
