### ISSUE TITLE
Launcher - Cannot move to Secondary Monitor

### ISSUE THREAD

**Issue by Corruptforce** [NCC-Lykos/neocron-classic#234] opened 2018-03-12 18:17 UTC
Cannot move the launcher window to a secondary monitor, seems to anchor somewhere in the middle, however gets stuck.

See video: [NCC Launcher Issues](https://www.youtube.com/watch?v=8TLoizc1KxE&feature=youtu.be)

Running latest Windows 10 Fall Creators edition.

**Comment by NCC-Lykos** [comment] 2018-03-12 18:32
We have confirmed this issue, also we have seen when running via Wine in OS X or macOS it will lock to the center of a random screen, and can only be moved vertical.

**Comment by Corruptforce** [comment] 2018-03-12 18:34
Workaround for windows is to navigate it between screens with WinKey + Shift + Left/Right arrow.

**Comment by M-ace** [comment] 2018-03-12 18:39
if u launch it from quick bar on second screen it will launch in that second screen.  but game will launch in first screen reguardless.

**Comment by ghost** [comment] 2019-02-02 06:19
With updates done with the launcher, I am no longer able to duplicate this issue.

I am using Windows 10, fully updated, and am able to move the launcher window between all three of my monitors.

**Comment by M-ace** [comment] 2019-02-02 19:55
its been a while, but i think the issue was launching the game in a
different window, not the launcher placement.  but its been a while so im
not really sure.

**Comment by ghost** [comment] 2019-02-03 01:13
The title of the issue is referring to the launcher. The video that was also posted was a demonstration of the launcher. The game loading on a specific monitor and/or movement between screens would be a seperate issue.

**Comment by M-ace** [comment] 2019-02-03 16:44
Ok. Thanx for clarity.  Like i said its been a long time and i really dont
remember. Heart

**Comment by NCC-Therenall** [comment] 2019-02-04 18:14
This is still an issue. I have this on all of my computers with high-DPI monitors.

On my laptop, I cannot move it between certain monitors. ie: I can move it between my laptop monitor and the 4k on the right. But I can't move it to the 4k on the left, and when I try it screws up the size of the window. 

I've also had this issue between my 4k and 3440x1440 monitors on my desktop.

**Comment by NCC-Therenall** [comment] 2019-02-04 18:19
Here's an example of what it does on my monitors on my laptop:

![launcher-issue](https://user-images.githubusercontent.com/32750893/52228109-83e08d80-287f-11e9-85e7-93df776f331a.PNG)
![retinope](https://user-images.githubusercontent.com/32750893/52228110-83e08d80-287f-11e9-88de-d67433ed4ca9.PNG)

Edit: To note this is in addition to it getting stuck mid-screen-transition. When it gets stuck, it does this to the size.

**Comment by NCC-Lykos** [comment] 2022-08-25 13:28
This is fixed in a new launcher build to be released.

**Closed as completed by NCC-Lykos** 2022-08-25 13:28 UTC
Labels: Launcher Issue
