### ISSUE TITLE
Tired Citymerc Guards

### ISSUE THREAD

**Issue by ghost** [NCC-Lykos/neocron-classic#32] opened 2017-10-15 17:29 UTC
- [ ] some of the citymercs guards fall into sleep screenshot here https://forum.neocron.org/threads/563-Tired-Citymerc-Guards

**Comment by NCC-Camarogue** [comment] 2017-10-18 18:45
i just went through all MB sectors and wasn't able to verify this issue. Either it was a glitch or the issue was raised during the time when we had problems with the healthupdate for certain mobs..
I'm going to close this as soon as someone else can confirm that everything is working as intended.

**Comment by NCC-Lykos** [comment] 2017-10-24 00:37
Seems okay to me.

**Closed as completed by NCC-Lykos** 2017-10-24 00:37 UTC
Labels: invalid
