### ISSUE TITLE
Crahn Epic ( Mission 4 ) do not work

### ISSUE THREAD

**Issue by Blackeast** [NCC-Lykos/neocron-classic#143] opened 2018-02-04 18:08 UTC
Mission 1-3 done
Mission 4 do not Work.
I Talk to the registrar in Brotherhood of Crahn HQ. and he tell me ( in the Wondow ) i must go to Father Agnus in Crahn Church in Outzone SEC-9.
The problem is I can not get any Mission, and Father Agnus takl only "cane i Help you" ( Normal conversation no Epic conversation )

**Comment by ghost** [comment] 2018-03-05 02:07
An observation with the Crahn epic.  When you start Missions 1-3, when you first take the mission, the NPC Pointer shows up immediately in front of the Registrar (showing what NPC you talk to, etc).

But, when you start Mission 4, it doesn't, and no NPC after that acts like you're even on a mission. 
 
Seems like Mission 4 isn't even "starting"

**Comment by ghost** [comment] 2018-09-10 21:43
Closing this since this epic has been confirmed working.  Current mission system bugs may be affecting some parts of this mission and have been referenced elsewhere.  Closing this out for now.

**Closed as completed by ghost** 2018-09-10 21:43 UTC
Labels: Content Dev, Missions
