### ISSUE TITLE
mb spawns mb storage areas

### ISSUE THREAD

**Issue by M-ace** [NCC-Lykos/neocron-classic#125] opened 2018-01-30 07:05 UTC
Why is it that when we first went in those storage places loads of 27/27 sentenals would spawn?  Now that im /19 they seem to have all dryed up? We were taking missions for those trying to level psi and had to clear the place out 3 times to complete the mission.  When I was 0/2 I walked into a room and there were 7 of them in 1 spot lol.  Insta death occurred lol.  We would kill everything (even those annoying flying mech things that are impossible to hit), but we got mostly cyberhounds, spiders ect.  Maybe it was just messed up cuz of the server wipe/reset. I dunno

**Comment by ghost** [comment] 2018-01-30 07:08
The odd spawns are due to the server being reset.  It takes it a little bit for the spawns to "get back on track" so to say.

The rank of the mobs that spawn in areas are not based off your ranks.

**Comment by M-ace** [comment] 2018-01-30 07:15
ok, i didnt think it was, but it sure seemed like it lol

**Comment by NCC-Lykos** [comment] 2018-01-30 16:06
Gonna go ahead and close this as its not a bug.

**Closed as completed by NCC-Lykos** 2018-01-30 16:06 UTC
Labels: Not a bug
