### ISSUE TITLE
Processor Times - Implanting/Research

### ISSUE THREAD

**Issue by Corruptforce** [NCC-Lykos/neocron-classic#229] opened 2018-03-12 13:17 UTC
Widely known bug, but could not be found in the tracker.

Processor times for implanting seem to be way off, putting in simple 2 chips seems to be the same speed as MC5 chips were in retail.

Some bones take upwards of a minute or two.

Ressing E parts taking 6 minutes etc.

**Comment by NCC-Lykos** [comment] 2018-03-12 16:45
This was confirmed, but is following the proper formula that was established in the source. It was literally broken before but fixed now. We would have to add a modifier to decrease the time now to find a happy medium but the way it is now is the way KK intended it lol 

Something in the new storage changes exposed a new bug, and we need to correct it so that times are not as long as they are now.

**Comment by Corruptforce** [comment] 2018-03-12 17:01
Man, KK were sadistic if they expected people to spend 150 hours researching parts!

I'm not surprised that the original speeds we all know and love were actually borne from a bug!

**Comment by M-ace** [comment] 2018-03-12 18:13
yea, as it is right now.  its game over if a rare or mc5 chip falls out after death.  and nobody wants e parts cuz of 6 minutes to ress 1 part.

**Comment by butterrmahjely** [comment] 2018-03-12 18:23
Maybe rewarding a runner for having 100+ implant in order to reduce implant/poke time. Same concept goes for researching rares which I think is the current function.

**Comment by NCC-Therenall** [comment] 2018-07-20 03:36
Just a heads up that I tracked this down to a content issue, the source part is working alright but the content is leaving out an action modifier for implant sub skill causing them to take a really long time.

Hoping it should be fixed soon / in the next patch.

**Comment by NCC-Lykos** [comment] 2018-10-13 19:30
Implants have been fixed.

**Closed as completed by NCC-Lykos** 2018-10-13 19:30 UTC
Labels: Bug, Content Dev
