### ISSUE TITLE
Team Bug

### ISSUE THREAD

**Issue by Blackeast** [NCC-Lykos/neocron-classic#121] opened 2018-01-29 21:38 UTC
Wehn 1 Player of me Team have a Fatal, the Team Clos Completle

**Comment by ghost** [comment] 2018-01-29 23:55
The player is dropped from team because they've been disconnected from the game. Once the last remaining teammate is dropped, the team no longer exists.

Teammates are dropped because you don't want a team of logged out players, as the team would fill up and nobody active left.

**Comment by Blackeast** [comment] 2018-01-30 00:35
OK.
I have 4 Player on my Team, only 1 have a Fatel and the Team are Closed.
This are Not a Bug?

**Comment by ghost** [comment] 2018-01-30 00:39
Thank you for clarifying. In the future please make sure to include as much information on the issue as possible. We can't diagnose and reproduce bugs without it.

**Comment by ghost** [comment] 2018-01-30 01:13
3-5 syncs and the team is closed... the fatal crash close the team too -.- team invites buggy  most time the message pops up runner is already in a team

**Comment by NCC-Lykos** [comment] 2018-01-30 01:31
I just verified this bug exists, teams are extremely buggy at the moment. We will do some work to them shortly.

**Comment by ghost** [comment] 2018-01-31 05:50
I know it's already been confirmed, but I wan't to add some more to this.

Tonight, MayhemMike and I were attempting to team, etc. Our names would show up for a split second in the Team Window, and drop out, and no nameplate showing up over your "teammate".  However, Team Chat between the two runners still functioned, as well as sharing of _Money ONLY_, no XP.  We both zoned, and we appeared back within the Team Window, and we were sharing XP and Money at that point.

Also, if I leave the team, the other runner cannot re-invite me as it says I'm still a member of said team. /shrug

**Comment by M-ace** [comment] 2018-02-01 08:07
i had this issue today with a friend also.  it said i cant invite someone already in a team. so we both relogged and resent the team invite.  it then worked.  not sure if we shared anything tho cuz i died before i could check lol

**Comment by Corruptforce** [comment] 2018-03-12 15:23
Can we please re assign as an issue/bug?

For example, if you zone out and back in - it will appear you are still teamed (nameplate indicator) but no money or XP will be shared.

Both members need to leave team and reinvite (VERY frustrating when running aggy missions).

I in fact didn't notice this until someone mentioned it whilst randomly grinding together, confirmed it multiple times.

@NCC-Lykos

**Comment by NCC-Therenall** [comment] 2018-07-03 15:29
So I'm pretty sure teams are fixed.

Can you guys test this and report back on here?

**Comment by NCC-Therenall** [comment] 2018-07-03 20:24
We had some guys test this internally. It seems like it's working, going to close this.

**Closed as completed by NCC-Therenall** 2018-07-03 20:24 UTC
Labels: Source Dev
