### ISSUE TITLE
Tangent technologies beginning quest.

### ISSUE THREAD

**Issue by Aeromozol** [NCC-Lykos/neocron-classic#294] opened 2018-06-13 14:48 UTC
First quest where you are supposed to deliver 2 packages and take 3rd.
1st package goes to Director of Operations at NEXT HQ. Nothing wrong there.
2nd package with alcohol should go to broker at Dimond real estate HQ in  plaza sector 3.
Instead of conversation broker offers apartmensts.
3nd package (should?) be obtained from Figaro at pepper park sector 3. He says that have nothig from me.

Link to wiki about mission. https://wiki.techhaven.org/EpicGuide:Tangent_Technologies#Mission_1_-_Delivery_-_Required_Rank:10

Tried to restart. Issue repeats.

**Comment by ghost** [comment] 2018-06-17 17:31
This is a duplicate of Issue #160.  Please search the issues before posting a new issue.

Also, TechHaven.org is no longer the correct place to reference when referring to Epic Runs on our server as some of them have been changed.  The correct place is https://wiki.neocron.org.

**Closed as completed by ghost** 2018-06-17 17:31 UTC
Labels: Duplicate
